In [4]:
import numpy as np

In [13]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.inv(mat))


[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
